### ISSUE TITLE
Store abstraction

### ISSUE THREAD

**Issue by ktec** [hexpm/diff#42] opened 2020-01-24 11:19 UTC
Just wanted to highlight some implementation leakage in the `Diff.Package.Store` module. If I understand the intent of the code correctly the `Store` module is an abstraction and `DefaultStore` is an implementation which relies on `:ets` to support it. That being the case, there shouldn't be any reference to `:ets` in the `Store` module - it should be encapsulated in `DefaultStore`.

Feel free to close this issue if you consider this unimportant detail.

Otherwise, happy to provide an PR if desired.

**Comment by joladev** [comment] 2020-01-24 11:31
The purpose for it is not to be an abstraction, it's just to make `get_names` and `get_versions` mockable. Check out the tests for the search view for how it's used https://github.com/hexpm/diff/blob/master/test/diff_web/live/search_view_test.exs. You could say the Store is not abstracted at all, just the "Store Front" (and that is just abstracted to support mocks).

I'll close this for now, but if you have ideas for how to improve the naming/organization of the modules to make the purpose clearer feel free to re-open with your thoughts 🙂

**Closed by joladev** 2020-01-24 11:31 UTC

**Comment by wojtekmach** [comment] 2020-01-24 13:39
I'd say changing this particular implementation & tests is probably a low-priority right now but something I'd personally be interested in nonetheless!

Seems Diff.Package.Store behaviour is just for making testing easier and not to make an important boundary in the system explicit. To me important boundaries are when there are multiple real implementations for a contract or when we're integrating with outside world. Thus, I'd arbitrarily say using a behaviour could be considered an overkill in this particular case and I can think of two other solutions to put the system under test in desired state:

1. instead of using Mox, which requires behaviour, we could dependency injection the module to the view as a socket assign. We switch an explicit contract (using behaviour) for an implicit one (which  in this case I don't mind) and we need to add some more logic to mount/3.

2. putting the desired state using public API so we can later read it back in the test. There already exists a Diff.Package.Store.fill/1 we could use. The problem is the ets table is public so without some extra work we'd have races.

so these are my two alternate testing strategies and neither seem like a net positive!
